apiVersion: multitenant-wrapper.multitenant.storageclass/v1
kind: NSStorageClass
metadata:
  labels:
    app.kubernetes.io/name: multitenant-storageclass-operator
    app.kubernetes.io/managed-by: kustomize
  name: nsstorageclass-sample
spec:
  provisioner: csi-driver.example-vendor.example
  reclaimPolicy: Retain # default value is Delete
  allowVolumeExpansion: true
  mountOptions:
    - discard # this might enable UNMAP / TRIM at the block storage layer
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    guaranteedReadWriteLatency: "true" # provider-specific
